"""Agent installer endpoints — serves install script and wheel from the running pod."""

from __future__ import annotations

import importlib.metadata
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import FileResponse, PlainTextResponse

router = APIRouter(prefix="/api/agent", tags=["agent-install"])

DIST_DIR = Path("/app/dist")


def _find_wheel() -> Path | None:
    """Find the kira wheel in /app/dist/."""
    if not DIST_DIR.exists():
        return None
    wheels = sorted(DIST_DIR.glob("kira-*.whl"), reverse=True)
    return wheels[0] if wheels else None


def _build_script(request: Request) -> str:
    """Build the install script with server URL and version baked in."""
    proto = request.headers.get("x-forwarded-proto", request.url.scheme)
    host = request.headers.get("x-forwarded-host", request.url.netloc)
    server_url = f"{proto}://{host}"
    version = importlib.metadata.version("kira")
    return _INSTALL_SCRIPT.replace("{{SERVER_URL}}", server_url).replace("{{VERSION}}", version)


@router.get("/install.sh")
async def install_script(request: Request):
    """Return a shell script that installs and starts the kira agent.

    Usage: curl -sSL https://kira.internal/api/agent/install.sh | bash
    """
    return PlainTextResponse(_build_script(request), media_type="text/x-shellscript")


@router.get("/install.command")
async def install_command(request: Request):
    """Download a .command file (double-clickable on macOS)."""
    script = _build_script(request)
    return PlainTextResponse(
        script,
        media_type="application/octet-stream",
        headers={"Content-Disposition": "attachment; filename=kira-agent-install.command"},
    )


@router.get("/package")
async def download_package():
    """Serve the kira wheel file for local installation."""
    wheel = _find_wheel()
    if wheel is None:
        return PlainTextResponse("No wheel found in /app/dist/", status_code=404)
    return FileResponse(
        wheel,
        media_type="application/octet-stream",
        filename=wheel.name,
    )


@router.get("/version")
async def agent_version(request: Request):
    """Return the current server version and install URL."""
    version = importlib.metadata.version("kira")
    wheel = _find_wheel()

    proto = request.headers.get("x-forwarded-proto", request.url.scheme)
    host = request.headers.get("x-forwarded-host", request.url.netloc)
    install_url = f"{proto}://{host}"

    return {
        "version": version,
        "install_url": install_url,
        "wheel_available": wheel is not None,
        "wheel_name": wheel.name if wheel else None,
    }


_INSTALL_SCRIPT = r"""#!/usr/bin/env bash
# Kira Agent — install, upgrade, or start
# Generated by Kira server at {{SERVER_URL}}
#
# Usage:
#   curl -sSL {{SERVER_URL}}/api/agent/install.sh | bash
#
# Idempotent: installs if missing, upgrades if outdated, always starts the agent.
#
set -euo pipefail

SERVER_VERSION="{{VERSION}}"
SERVER="{{SERVER_URL}}"
KIRA_HOME="${KIRA_HOME:-$HOME/.kira}"
VENV_DIR="$KIRA_HOME/venv"
KIRA_BIN="$VENV_DIR/bin/kira"

header() { printf "\n  \033[1;36m%s\033[0m\n" "$1"; }
info()   { printf "  \033[0;37m%s\033[0m\n" "$1"; }
ok()     { printf "  \033[0;32m✓\033[0m %s\n" "$1"; }
warn()   { printf "  \033[0;33m!\033[0m %s\n" "$1"; }
fail()   { printf "  \033[0;31m✗\033[0m %s\n" "$1"; exit 1; }

header "Kira Agent v${SERVER_VERSION}"
info "Server: ${SERVER}"

# ---- Check if already installed and up-to-date ----
NEEDS_INSTALL=true
if [ -x "$KIRA_BIN" ]; then
    CURRENT_VERSION=$("$KIRA_BIN" version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "0.0.0")
    if [ "$CURRENT_VERSION" = "$SERVER_VERSION" ]; then
        NEEDS_INSTALL=false
        ok "Already installed (v${CURRENT_VERSION})"
    else
        info "Upgrading v${CURRENT_VERSION} → v${SERVER_VERSION}..."
    fi
fi

# ---- Install / upgrade if needed ----
if [ "$NEEDS_INSTALL" = true ]; then

    # Check Python
    PYTHON=""
    for candidate in python3.12 python3.13 python3; do
        if command -v "$candidate" &>/dev/null; then
            py_ver=$("$candidate" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "0.0")
            major=${py_ver%%.*}
            minor=${py_ver##*.}
            if [ "$major" -ge 3 ] && [ "$minor" -ge 12 ]; then
                PYTHON="$candidate"
                break
            fi
        fi
    done
    [ -z "$PYTHON" ] && fail "Python 3.12+ is required. Install from https://python.org/downloads/"
    info "Python: $($PYTHON --version)"

    # Create or reuse venv
    if [ ! -d "$VENV_DIR" ]; then
        info "Creating environment..."
        mkdir -p "$KIRA_HOME"
        "$PYTHON" -m venv "$VENV_DIR"
    fi

    # Download wheel (preserve correct filename for pip)
    info "Downloading kira ${SERVER_VERSION}..."
    WHEEL_PATH="$KIRA_HOME/kira-${SERVER_VERSION}-py3-none-any.whl"
    curl -sSfL -o "$WHEEL_PATH" "${SERVER}/api/agent/package" || fail "Download failed. Is the server reachable?"

    # Install
    info "Installing..."
    "$VENV_DIR/bin/pip" install --quiet --upgrade "$WHEEL_PATH" || fail "pip install failed"
    rm -f "$WHEEL_PATH"

    # Symlink to PATH
    LOCAL_BIN="$HOME/.local/bin"
    mkdir -p "$LOCAL_BIN"
    ln -sf "$KIRA_BIN" "$LOCAL_BIN/kira"

    if [ -w "/usr/local/bin" ] 2>/dev/null; then
        ln -sf "$KIRA_BIN" "/usr/local/bin/kira"
    fi

    ok "Installed kira v${SERVER_VERSION}"

    # Install system service (launchd / systemd)
    "$KIRA_BIN" agent install 2>/dev/null && ok "System service installed" || warn "Service install skipped (run 'kira agent install' manually)"
fi

# ---- Ensure agent is running ----
PIDFILE="$KIRA_HOME/agent.pid"
ALREADY_RUNNING=false

if [ -f "$PIDFILE" ]; then
    OLD_PID=$(cat "$PIDFILE" 2>/dev/null || echo "")
    if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
        if [ "$NEEDS_INSTALL" = true ]; then
            # Upgraded — restart to pick up new version
            info "Restarting agent with new version..."
            kill "$OLD_PID" 2>/dev/null || true
            sleep 2
        else
            ALREADY_RUNNING=true
            ok "Agent already running (pid $OLD_PID)"
        fi
    fi
fi

if [ "$ALREADY_RUNNING" = false ]; then
    header "Starting agent..."
    nohup "$KIRA_BIN" agent start > "$KIRA_HOME/agent.log" 2>&1 &
    AGENT_PID=$!
    echo "$AGENT_PID" > "$PIDFILE"

    sleep 1
    if kill -0 "$AGENT_PID" 2>/dev/null; then
        ok "Agent running (pid $AGENT_PID)"
    else
        # launchd/systemd may have started it already
        if [ -f "$PIDFILE" ]; then
            SVC_PID=$(cat "$PIDFILE" 2>/dev/null || echo "")
            if [ -n "$SVC_PID" ] && kill -0 "$SVC_PID" 2>/dev/null; then
                ok "Agent running via system service (pid $SVC_PID)"
            else
                warn "Agent may have failed to start. Check: $KIRA_HOME/agent.log"
            fi
        fi
    fi
fi

echo ""
info "Return to your browser — the agent status should turn green."
echo ""
"""
